;;;
; To enable a module, remove the semi-colon (;) in front of its name.
; If it's not here, simply add it its name, one per line.
;;;

fun
engine
fakemeta
;geoip
;sockets
regex
nvault
hamsandwich
reapi
json
sqlx
PersistentDataStorage
